export default [
  {
    id: 1,
    name: 'Siemens mitarbeiter',
    customers: [],
  },{
    id: 2,
    name: 'Bootcamp mittwoch abends',
    customers: [],
  },{
    id: 3,
    name: 'Rehaphase 1-A',
    customers: [],
  },,{
    id: 4,
    name: 'Rehaphase 1-B',
    customers: [{
       id:"657",
       first_name:"Rafael",
       last_name:"Diaz",
       email:"diaz_rafael_tmp@yahoo.com",
       phone_nr:"+49 12 34567890",
       street:"",
       city:"",
       zip_code:"",
       country:"DE",
       note:"",
       gender:"0",
       deleted:"0",
       last_change:"2018-06-04 13:41:27",
       language:"DE",
       birthday:"1970-01-01 00:00:00",
       role:"3",
       role:"3",
       privacy:"1"
    },
    {
       id:"848",
       first_name:"Rafael",
       last_name:"Diaz",
       email:"sync@lanista-training.com",
       phone_nr:"+49 12 34567890",
       street:"",
       city:"",
       zip_code:"",
       country:"DE",
       note:"",
       gender:"0",
       deleted:"0",
       last_change:"2018-05-24 14:05:54",
       language:"DE",
       birthday:"1973-08-03 00:00:00",
       role:"3",
       role:"3",
       privacy:"1"
    },
    {
       id:"2238",
       first_name:"Steffi",
       last_name:"Varner",
       email:"sb@test-customer.com",
       phone_nr:"+496412368745",
       street:"",
       city:"",
       zip_code:"",
       country:"DE",
       note:"",
       gender:"1",
       deleted:"0",
       last_change:"2018-06-27 15:20:39",
       language:"DE",
       birthday:"1980-01-01 00:00:00",
       role:"3",
       role:"3",
       privacy:"1"
    }],
  },
]
